name: Docker Image CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: build fauria/lamp
        run: docker build -t fauria/lamp docker-lamp

      - name: Build Toxantron/scrumonline/
        run: docker build -t ${GITHUB_REPOSITORY}:latest scrumonline/docker

      - name: Build our stateless version
        run: docker build -t ${GITHUB_REPOSITORY}-stateless:latest .

      - name: Docker login
        if: github.ref == 'refs/heads/master'
        env:
          docker_username: ${{ secrets.docker_username }}
          docker_password: ${{ secrets.docker_password }}
        run: docker login  -u $docker_username -p ${docker_password}

      - name: Tag
        run: docker tag ${GITHUB_REPOSITORY}:latest ${GITHUB_REPOSITORY}:${GITHUB_SHA}

      - name: Push latest
        if: github.ref == 'refs/heads/master'
        run: docker push ${GITHUB_REPOSITORY}:latest

      - name: Push sha
        if: github.ref == 'refs/heads/master'
        run: docker push ${GITHUB_REPOSITORY}:${GITHUB_SHA}

      - name: Tag
        run: docker tag ${GITHUB_REPOSITORY}-stateless:latest ${GITHUB_REPOSITORY}-stateless:${GITHUB_SHA}

      - name: Push latest
        if: github.ref == 'refs/heads/master'
        run: docker push ${GITHUB_REPOSITORY}-stateless:latest

      - name: Push sha
        if: github.ref == 'refs/heads/master'
        run: docker push ${GITHUB_REPOSITORY}-stateless:${GITHUB_SHA}
